package fr.gaulupeau.apps.Poche.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ARTICLE".
 */
public class Article {

    private Long id;
    private Integer articleId;
    private String content;
    private String author;
    private String title;
    private String url;
    private Boolean favorite;
    private Boolean archive;
    private Boolean sync;
    private java.util.Date updateDate;
    private Double articleProgress;

    public Article() {
    }

    public Article(Long id) {
        this.id = id;
    }

    public Article(Long id, Integer articleId, String content, String author, String title, String url, Boolean favorite, Boolean archive, Boolean sync, java.util.Date updateDate, Double articleProgress) {
        this.id = id;
        this.articleId = articleId;
        this.content = content;
        this.author = author;
        this.title = title;
        this.url = url;
        this.favorite = favorite;
        this.archive = archive;
        this.sync = sync;
        this.updateDate = updateDate;
        this.articleProgress = articleProgress;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Boolean getFavorite() {
        return favorite;
    }

    public void setFavorite(Boolean favorite) {
        this.favorite = favorite;
    }

    public Boolean getArchive() {
        return archive;
    }

    public void setArchive(Boolean archive) {
        this.archive = archive;
    }

    public Boolean getSync() {
        return sync;
    }

    public void setSync(Boolean sync) {
        this.sync = sync;
    }

    public java.util.Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(java.util.Date updateDate) {
        this.updateDate = updateDate;
    }

    public Double getArticleProgress() {
        return articleProgress;
    }

    public void setArticleProgress(Double articleProgress) {
        this.articleProgress = articleProgress;
    }

}
