package fr.gaulupeau.apps.Poche.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "QUEUE_ITEM".
 */
public class QueueItem {

    private Long id;
    private Long queueNumber;
    private int action;
    private Integer articleId;
    private String extra;

    public QueueItem() {
    }

    public QueueItem(Long id) {
        this.id = id;
    }

    public QueueItem(Long id, Long queueNumber, int action, Integer articleId, String extra) {
        this.id = id;
        this.queueNumber = queueNumber;
        this.action = action;
        this.articleId = articleId;
        this.extra = extra;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getQueueNumber() {
        return queueNumber;
    }

    public void setQueueNumber(Long queueNumber) {
        this.queueNumber = queueNumber;
    }

    public int getAction() {
        return action;
    }

    public void setAction(int action) {
        this.action = action;
    }

    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public String getExtra() {
        return extra;
    }

    public void setExtra(String extra) {
        this.extra = extra;
    }

}
